.eslintrc.json
.prettierrc.json
README.md
certification-references/dd-1.7/lookupMap.js
certification-references/dd-1.7/standardMeta.js
config.json
etl/processDataAvailabilityReport.js
index.js
package-lock.json
package.json
test/test.js
utils/batchTestRunner.js
utils/postResultsToApi.js
utils/restoreCertServerFromPath.js

This covers the migration of existing code from the RESO Commander repo.

Issue #1: Migrate code from RESO Commander repo

---

.eslintrc.json
.github/workflows/codecheck.yml
etl/processDataAvailabilityReport.js
index.js
utils/batchTestRunner.js
utils/postResultsToApi.js

* Stricter Linting
* Fixed Console Issues
See #5

Issue #5 Fix Linting Issues

---

etl/process-data-availability-report.js
package-lock.json

Addresses issues with availability calculations outlined in #13.

Issue #13: updated availability totals calculation

---

common.js
utils/batch-test-runner/runner.js
utils/batch-test-runner/sample-config.json

Adds support for OriginatingSystemName and OriginatingSystemID, among other enhancements.

#21: added support for OriginatingSystemName and OriginatingSystemID

---

data-access/cert-api-client.js
index.js
package-lock.json
utils/restore-utils/README.md
utils/restore-utils/index.js

#34: Removed overwrite - always push new passed reports

---

package.json

Updated package.json to point to LICENSE.

Update package.json to point to LICENSE

---

.eslintrc.json
index.js
lib/replication/README.md
lib/replication/index.js
lib/replication/services/auth/oauth2.js
lib/replication/utils.js
lib/schema/generate.js
lib/schema/index.js
lib/schema/utils.js
lib/schema/validate.js

This adds schema validation to the sampling runs. See #54. 
Note that there are currently issues with the schema validation reports. This will be addressed in another ticket.

#60 Add schema validation to sampling

---

common.js
lib/schema/generate.js
lib/schema/index.js
lib/schema/utils.js
lib/schema/validate.js

#62: schema validation issues

---

lib/schema/utils.js
lib/schema/validate.js

#62: validation changes

---

package-lock.json

#73: Update Cert Artifacts

---

index.js
lib/schema/generate.js
lib/schema/index.js
lib/schema/utils.js
lib/schema/validate.js
sample.env
test/generate.js
test/schema/metadata-samples.js
test/schema/payload-samples.js
test/schema/schema-samples.js
test/test.js
test/validation.js

closes #62 
another attempt at fixing string list validation and other issues. tested with the reso-autofill-10k locally.

#62: string list validation issue and tests

---

common.js
index.js
lib/certification/README.md
lib/variations/README.md
lib/variations/index.js
lib/variations/utils.js
sample.env

#77: Add CSV util to push variations into service

---

README.md
lib/replication/utils.js

#80: Updated URL for count

---

lib/misc/index.js
lib/replication/utils.js
lib/restore/index.js
lib/variations/index.js
package-lock.json
package.json
test/validation.js

Closing #82.
Locked the version to a specific commit for controlled updates. Will need to update accordingly when there are major changes to ETL.

#82: Update RESO Certification ETL

---

.gitignore
package-lock.json
package.json

#85: Updated ETL version and .gitignore

---

index.js
lib/replication/index.js
lib/replication/replication-iterator.js
lib/replication/utils.js

#87: Fixed max page size header issue

---

lib/schema/validate.js

Closing #91. 
Tested and seems to work.

#91: Add maxlength warning for non string type

---

lib/schema/generate.js
lib/schema/validate.js
test/schema/payload-samples.js
test/validation.js

closes #94
see https://github.com/RESOStandards/reso-certification-utils/issues/94#issuecomment-1903423440

#94: Schema validation issues

---

README.md
common.js
lib/certification/README.md
lib/certification/index.js
lib/replication/index.js
lib/replication/services/auth/oauth2.js
lib/replication/utils.js
lib/schema/README.md
lib/variations/README.md
lib/variations/index.js
lib/variations/utils.js
sample.env

#79: Added support for fetching auth tokens from the Cert API

---

lib/schema/generate.js

#100: Ignore scale and precision on integers

---

lib/certification/index.js
lib/variations/index.js
test/variations.js

#90: Restricted substring matching to items at least min length

---

lib/replication/index.js
lib/schema/validate.js

#108: Removed version selection info for OData context

---

lib/variations/index.js

#113: Added batching for updateVariations

---

lib/schema/validate.js

#115: Disable AJV Caching

---

index.js
lib/variations/index.js
lib/variations/utils.js

#123: Add Admin, Fast Track, and Suggestions flags to update

---

lib/schema/generate.js
lib/schema/validate.js
test/schema/payload-samples.js
test/schema/schema-samples.js
test/validation.js

#118: Schema validation issues for enumerations

---

.gitignore
schema-validation-settings.json

Added default schema validation settings.

Add default schema validation settings

---

package-lock.json
package.json

#129: Updated DD 2.0 reference artifacts

---

index.js
lib/variations/index.js

#131: Added util to inflate mappings

---

lib/schema/validate.js
test/validation.js

#128: Schema validation undefined null error

---

package-lock.json
package.json

#135: Updated ETL lib with new DD 2.0 references

---

.github/workflows/codecheck.yml
common.js
lib/schema/validate.js
test/schema/payload-samples.js
test/schema/schema-samples.js
test/validation.js

#139: Fix resource and field names for expansion errors

---

lib/certification/index.js
lib/replication/index.js
lib/replication/replication-iterator.js
lib/replication/utils.js
lib/variations/index.js

#141: Update how schema validation file is handled

---

lib/replication/index.js
lib/schema/utils.js
lib/schema/validate.js
test/validation.js

closes #111
This PR adds changes so that we can keep track of the schemas that have been compiled with a map. We can then re-use the schema or force a recompile based on the map.

#111: AJV caching issue

---

common.js
lib/schema/validate.js
package-lock.json
package.json
test/schema/payload-samples.js
test/schema/schema-samples.js
test/validation.js

#143: Schema validation throws error for nullable expansions

---

.eslintrc.json
lib/schema/context.js
lib/schema/utils.js
lib/schema/validate.js
test/schema/payload-samples.js
test/validation.js

#145: Validation step dropping dd elements

---

lib/schema/utils.js
test/schema/payload-samples.js
test/validation.js

#149: Odata simple identifier false negatives

---

common.js
lib/variations/index.js
package-lock.json
package.json
test/schema/schema-samples.js

Reverts RESOStandards/reso-certification-utils#155
Found Variations matching issue with merged changes. Will address as a separate ticket.

Revert "#148 Update metadata references and matching"

---

package-lock.json
package.json

#159: Updated metadata references

---

lib/schema/validate.js
test/schema/payload-samples.js
test/validation.js

#163: Schema validation incorrect resource name classification

---

index.js
lib/certification/upi/README.md
lib/certification/upi/index.js
lib/upi/country-subdivisions/index.js

#167: Updated READMEs and added path resolution

---

common.js
lib/certification/data-dictionary/index.js
lib/replication/index.js
lib/replication/utils.js
lib/schema/index.js

Also updated loggers and fixed some minor issues.

#173: Updated paths to be fully qualified

---

lib/schema/utils.js
package-lock.json
package.json

#180: DD 2.0 Errata - Sept 2024

---

package-lock.json
package.json

#182: DD 2.0 Errata, Sept 20 2024

---

lib/replication/index.js
lib/replication/services/auth/oauth2.js

#191: Reset auth service prior to replication

---

package-lock.json
package.json

#193: DD 2.0 Updates - Oct 2024

---

index.js
lib/schema/README.md
lib/schema/context.js
lib/schema/index.js
lib/schema/utils.js
lib/schema/validate.js
test/validation.js

#202: Optimize validation process and change error report structure

---

lib/replication/utils.js
test/replication.js

#207: Fix replication scorepayload error

---

lib/schema/utils.js
test/schema/payload-samples.js
test/validation.js

#175: Fix comma issue in lookups in schema validation
